// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Data
{
    public partial class Photo
    {
        public int Id { get; set; }
        public int PlatformUserId { get; set; }
        public string PublicId { get; set; }
        public int IsMain { get; set; }
        public string Url { get; set; }

        public virtual User PlatformUser { get; set; }
    }
}