// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API.Data
{
    public partial class User
    {
        public User()
        {
            Photo = new HashSet<Photo>();
            LikedUser = new HashSet<User>();
            SourceUser = new HashSet<User>();
        }

        public int Id { get; set; }
        public string UserName { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string KnownAs { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? LastActive { get; set; }
        public string Gender { get; set; }
        public string Introduction { get; set; }
        public string LookingFor { get; set; }
        public string Interests { get; set; }
        public string City { get; set; }
        public string Country { get; set; }

        public virtual ICollection<Photo> Photo { get; set; }

        public virtual ICollection<User> LikedUser { get; set; }
        public virtual ICollection<User> SourceUser { get; set; }
    }
}